- title: Algorithms Notes For Professionals
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: Algorithms Notes For Professionals.pdf
- title: Algorithms For Decision Making
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: Algorithms for Decision Making.pdf
- title: C++ Programming
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: C++ Programming.pdf
- title: C++ Tapestry 2
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: C++ Tapestry 2.pdf
- title: Cyberpunk 2077 No Coincidence
  author: Unknown
  genre: Sci-Fi
  summary: No summary provided.
  cover: ""
  tags: []
  file: Cyberpunk 2077 No Coincidence.epub
- title: Foundations Of Machine Learning
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: Foundations of Machine Learning.pdf
- title: How It Works…The Computer
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: How It Works…The Computer.pdf
- title: The Prince
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: The Prince.epub
- title: Understanding Machine Learning
  author: Unknown
  genre: Uncategorized
  summary: No summary provided.
  cover: ""
  tags: []
  file: Understanding Machine Learning.pdf
